python training-script.py \
    --data_dir=./dataset \
    --batch_size=4 \
    --epochs 20 \
    --lr 0.001 \
    --alpha 0.5 \
    --beta 0.5 \
    --pretrain_epochs 5 \
    --save_dir ./checkpoints \
    --vis_dir ./visualizations \
    --resume 0 \
    --img_size 144 \
    --pretrain \
    --num_heads 2 2 2 2 \
    --depths 2 2 2 2 \
    --embed_dim 32 \
    --window_size 4